### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by sysu17363099** [peterwestuw/GPT2ForwardBackward#1]
Hello! Do the “forward" and "backward"  mean that you have trained the model which could generate words from two directions？By coincidence, I want to train the gpt2 for backward but I can't find any pretrained model but here. At the same time, it is not unrealistic for me to train it from scratch. If you have the pretrained model, could I trouble you to share the model? (My English is not very good, please excuse me）. Thank you !

**Comment by peterwestuw** [comment]
We were not able to make changes to this repo as it was associated with a paper under anonymous review. We have added the model weights now!
