### ISSUE TITLE
How to increase number of tokens generated?

### ISSUE THREAD

**Issue by GenTxt** [peterwestuw/GPT2ForwardBackward#3]
Thanks for the repo. I have your 'backward model' example working but when I increase the number of words in 'input_text = ' the following error is generated:

Input length of input_ids is 22, but ``max_length`` is set to 20. This can lead to unexpected behavior. You should consider increasing ``config.max_length`` or ``max_length``

I have set these values before in other scripts (e.g. max_length=512) but I am unclear where these should be added or modified.

Also, could you provide an example of how to generate the max tokens for this model which I assume is 1024?

Cheers.

**Comment by peterwestuw** [comment]
Great question! These models effectively extend the huggingface transformers pretrained model class. As such, functions like generate are actually just inherited from huggingface. The relevant function is here:

https://huggingface.co/transformers/_modules/transformers/generation_utils.html#GenerationMixin.generate

In short, you'll want to change the `max_length` and `min_length` parameters for the generate function. Also note that these parameters *include* the input length, so if you want to generate exactly 10 tokens you would want something like: `model.generate(..., max_length = n_input_tokens  + 10, min_length = n_input_tokens  + 10)`
